---
version: '2'
services:
  apache:
    build:
      context: '.'
      dockerfile: "Dockerfile.apache"
    image: "centos7_httpd:latest"
    labels:
      edu.harvard.fas.rc.description: "simple apache config"
      edu.harvard.fas.rc.customer: "internal"
      edu.harvard.fas.rc.type: "web"
      edu.harvard.fas.rc.database: "false"
      edu.harvard.fas.rc.ticket: "99999999"
    ports:
      - "443:443"
      - "80:80"
    expose:
      - "443"
      - "80"
    links:
      - shiny
    volumes:
      - ./10_shiny.conf:/etc/httpd/conf.d/000_default.conf
  shiny:
    build:
      context: '.'
      dockerfile: "Dockerfile.shiny"
    image: "fasrc/rshiny_pro_centos:compose"
    labels:
      edu.harvard.fas.rc.description: "shiny r web frontend"
      edu.harvard.fas.rc.customer: "internal"
      edu.harvard.fas.rc.type: "web"
      edu.harvard.fas.rc.database: "false"
      edu.harvard.fas.rc.ticket: "99999999"
    ports:
     - "3838"
    expose:
     - "3838"
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - ./test:/srv/shiny-server/test
