---
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  shiny:
    build:
      context: '.'
      dockerfile: "Dockerfile.shiny"
    image: "fasrc/rshiny_pro_centos:compose"
    labels:
      edu.harvard.fas.rc.description: "shiny r web frontend"
      edu.harvard.fas.rc.customer: "internal"
      edu.harvard.fas.rc.type: "web"
      edu.harvard.fas.rc.database: "false"
      edu.harvard.fas.rc.ticket: "99999999"
    ports:
      - "3838"
    volumes:
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf
      - ./test:/srv/shiny-server/test
    environment:
      - VIRTUAL_HOST="192.168.99.100"
      - VIRTUAL_PORT="3838"
